id: P003112
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2CZ8096
  title: མཛོད་འགྲེལ་མངོན་པའི་རྒྱན
  author: ''
  volumes:
    58ed1fce213e4c67987897d15075de13:
      image_group_id: I1PD97353
      title: ''
      volume_number: 1
      total_pages: 1728
      base_file: v001.txt
