id: I9D56B5E3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T17:38:46+00:00'
last_modified: '2022-06-07T17:40:29.854324+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8096
  title: མཛོད་འགྲེལ་མངོན་པའི་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '0062':
      image_group_id: I1PD97353
      title: ''
      total_pages: 1728
      order: 1
      base_file: 0062.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
