id: I9D56B5E3
legacy_id: P003112
ocr_import_info:
  bdrc_scan_id: W2CZ8096
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T17:29:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T16:08:02.174264+00:00'
last_modified: 2022-09-03 00:12:35.553533
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ8096
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ8096
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཛོད་འགྲེལ་མངོན་པའི་རྒྱན།
  author: མཆིམས་འཇམ་པའི་དབྱངས།
statistics:
  ocr_word_mean_confidence_index: 0.5285375376794873
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1PD97353:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD97353
      total_pages: 1728
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD97353.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5285375376794873
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
